// <auto-generated />
using BeadDotNetApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeadDotNetApp.Migrations.Finding
{
    [DbContext(typeof(FindingContext))]
    [Migration("20181110215500_InitialCreateFinding")]
    partial class InitialCreateFinding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BeadDotNetApp.Models.Finding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<string>("FindingCategory");

                    b.Property<double>("Length_CM");

                    b.Property<string>("Material");

                    b.Property<double>("Price_Point");

                    b.HasKey("ID");

                    b.ToTable("Finding");
                });
#pragma warning restore 612, 618
        }
    }
}
