// <auto-generated />
using System;
using BeadDotNetApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeadDotNetApp.Migrations.StoreList
{
    [DbContext(typeof(StoreListContext))]
    [Migration("20181206005710_InitialCreateStoreList")]
    partial class InitialCreateStoreList
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BeadDotNetApp.Models.Bead", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Color");

                    b.Property<string>("Material");

                    b.Property<decimal>("PricePoint");

                    b.Property<int>("Quantity");

                    b.Property<string>("Shape");

                    b.Property<int>("SizeMM");

                    b.Property<int?>("StoreListID");

                    b.HasKey("ID");

                    b.HasIndex("StoreListID");

                    b.ToTable("Bead");
                });

            modelBuilder.Entity("BeadDotNetApp.Models.Finding", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<string>("FindingCategory");

                    b.Property<double>("Length_CM");

                    b.Property<string>("Material");

                    b.Property<double>("Price_Point");

                    b.Property<int?>("StoreListID");

                    b.HasKey("ID");

                    b.HasIndex("StoreListID");

                    b.ToTable("Finding");
                });

            modelBuilder.Entity("BeadDotNetApp.Models.StoreList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.ToTable("StoreList");
                });

            modelBuilder.Entity("BeadDotNetApp.Models.StringingMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Category");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<string>("Material");

                    b.Property<double>("Price_Per_Foot");

                    b.Property<int?>("StoreListID");

                    b.HasKey("ID");

                    b.HasIndex("StoreListID");

                    b.ToTable("StringingMaterial");
                });

            modelBuilder.Entity("BeadDotNetApp.Models.Bead", b =>
                {
                    b.HasOne("BeadDotNetApp.Models.StoreList")
                        .WithMany("beads")
                        .HasForeignKey("StoreListID");
                });

            modelBuilder.Entity("BeadDotNetApp.Models.Finding", b =>
                {
                    b.HasOne("BeadDotNetApp.Models.StoreList")
                        .WithMany("findings")
                        .HasForeignKey("StoreListID");
                });

            modelBuilder.Entity("BeadDotNetApp.Models.StringingMaterial", b =>
                {
                    b.HasOne("BeadDotNetApp.Models.StoreList")
                        .WithMany("stringingMaterial")
                        .HasForeignKey("StoreListID");
                });
#pragma warning restore 612, 618
        }
    }
}
