// <auto-generated />
using BeadDotNetApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeadDotNetApp.Migrations.StringingMaterial
{
    [DbContext(typeof(StringingMaterialContext))]
    [Migration("20181111200106_InitialCreateStrMtrl")]
    partial class InitialCreateStrMtrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BeadDotNetApp.Models.StringingMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Category");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<string>("Material");

                    b.Property<double>("Price_Per_Foot");

                    b.HasKey("ID");

                    b.ToTable("StringingMaterial");
                });
#pragma warning restore 612, 618
        }
    }
}
